baseurl: /blog
url: http://haifengwang.github.io/blog
markdown: redcarpet
redcarpet: 
	extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
safe: false
paginate: 10